variable "name" {}
variable "location" {}
variable "vnetcidr" {}
variable "websubnetcidr" {}
variable "appsubnetcidr" {}
variable "dbsubnetcidr" {}
variable "appgwsubnetcidr" {}
variable "web_host_name" {}
variable "web_username" {}
variable "web_os_password" {}
variable "app_host_name" {}
variable "app_username" {}
variable "app_os_password" {}
variable "primary_database" {}
variable "storage_account_name" {}
variable "primary_database_admin" {}
variable "primary_database_password" {}
variable "primary_database_version" {}
variable "resource_group" {}